# 2.行列積

In [146]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

$$
  \boldsymbol{ab} = 
  \left[\begin{array}{c}
    a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} & a_{11}b_{13}+a_{12}b_{23}+a_{13}b_{33} \\
    a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32} & a_{21}b_{13}+a_{22}b_{23}+a_{23}b_{33} \\
    a_{31}b_{11}+a_{32}b_{21}+a_{33}b_{31} & a_{31}b_{12}+a_{32}b_{22}+a_{33}b_{32} & a_{31}b_{13}+a_{32}b_{23}+a_{33}b_{33} \\
  \end{array}\right] \quad
$$ \\
$$
  \boldsymbol{ab} = 
  \left[\begin{array}{c}
    (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
    4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
    7\times0+8\times0+(-9)\times2 & 7\times2+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1) \\
  \end{array}\right] \quad
$$\\
$$
  \boldsymbol{ab} = 
  \left[\begin{array}{c}
    6 & 29 & -20 \\
    12 & 52 & 38 \\
    -18 & -51 & -48 \\
  \end{array}\right] \quad
$$


##【問題２】NumPyの関数による計算

この行列積はNumPyのnm.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。
今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。
If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.



In [147]:
ab_ndarray_matmul = np.matmul(a_ndarray, b_ndarray)
ab_ndarray_dot = np.dot(a_ndarray, b_ndarray)
ab_ndarray3 = a_ndarray @ b_ndarray
print('{}\n'.format(ab_ndarray_matmul))
print('{}\n'.format(ab_ndarray_dot))
print('{}\n'.format(ab_ndarray3))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]



#3.行列積のスクラッチ実装

##【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1. 行列Aの(0,0)の要素 $a_{0,0}$と行列Bの(0,0)の要素 $b_{0,0}$を掛け合わせる
2. 行列Aの(0,1)の要素 $a_{0,1}$と行列Bの(1,0)の要素 $b_{1,0}$を掛け合わせる
3. 行列Aの(0,2)の要素 $a_{0,2}$と行列Bの(2,0)の要素 $b_{2,0}$を掛け合わせる
4. それらの値を全て足し合わせる

数式で表すと
$$
\sum_{k=0}^{2} a_{0,k} b_{k,0}
$$
です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

$a_{i,j}$\
$b_{j,k}$

In [148]:
def get_matrix_product1(matrix1, matrix2):
  list1 = matrix1.tolist()
  list2 = matrix2.tolist()
  result = [[sum([list1[i][j]*list2[j][k] for j in range(matrix1.shape[1])]) for k in range(matrix2.shape[1])] for i in range(matrix1.shape[0])]
  result = np.array(result).reshape(matrix1.shape[0], matrix2.shape[1])
  return result

### 計算前にリスト化しなくても計算できた↓

In [149]:
def get_matrix_product2(matrix1, matrix2):
  result = [[sum([matrix1[i,j]*matrix2[j,k] for j in range(matrix1.shape[1])]) for k in range(matrix2.shape[1])] for i in range(matrix1.shape[0])]
  result = np.array(result).reshape(matrix1.shape[0], matrix2.shape[1])
  return result

In [150]:
c = get_matrix_product2(a_ndarray, b_ndarray)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


##【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である 3 × 3 の行列Cの各要素 $c_{i,j}$ は数式で表すと次のようになります。

$$
c_{i,j} = \sum_{k=0}^{2} a_{i,k} b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$や $j$ を1増やすと、次の行や列に移ることができます。



###【解答】問題３でユーザ関数を定義済み

#4.行列積が定義されない組み合わせの行列


次に以下のような例を考えます。

$$
  \boldsymbol{D} = 
  \left[\begin{array}{c}
    -1 & 2 & 3 \\
    4 & -5 & 6 \\
  \end{array}\right] \quad,
  \boldsymbol{E} = 
  \left[\begin{array}{c}
    -9 & 8 & 7 \\
    6 & -5 & 4 \\
  \end{array}\right] \quad
$$
``d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])``

``e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])``

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。



##【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [151]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [152]:
def get_matrix_product(matrix1, matrix2):
  try:
    result = [[sum([matrix1[i,j]*matrix2[j,k] for j in range(matrix1.shape[1])]) for k in range(matrix2.shape[1])] for i in range(matrix1.shape[0])]
    result = np.array(result).reshape(matrix1.shape[0], matrix2.shape[1])
  except IndexError:
    print('Error: cannot calculate matrix product by the matrix combination you inputted.')
    print('matrix1: {} rows {} columns'.format(matrix1.shape[0], matrix1.shape[1]))
    print('matrix2: {} rows {} columns'.format(matrix2.shape[0], matrix2.shape[1]))
  return result

In [153]:
f = get_matrix_product(d_ndarray, e_ndarray)

Error: cannot calculate matrix product by the matrix combination you inputted.
matrix1: 2 rows 3 columns
matrix2: 2 rows 3 columns


UnboundLocalError: ignored

##【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [154]:
def get_matrix_product_t(matrix1, matrix2):
  try:
    matrix1 = matrix1.T
    result = [[sum([matrix1[i,j]*matrix2[j,k] for j in range(matrix1.shape[1])]) for k in range(matrix2.shape[1])] for i in range(matrix1.shape[0])]
    result = np.array(result).reshape(matrix1.shape[0], matrix2.shape[1])
  except IndexError:
    print('Error: cannot calculate matrix product by the matrix combination you inputted.')
    print('matrix1: {} rows {} columns'.format(matrix1.shape[0], matrix1.shape[1]))
    print('matrix2: {} rows {} columns'.format(matrix2.shape[0], matrix2.shape[1]))
  return result

In [155]:
g = get_matrix_product_t(e_ndarray, e_ndarray)
print(g)
print('\n')
g2 = get_matrix_product_t(d_ndarray, e_ndarray)
print(g2)

[[ 117 -102  -39]
 [-102   89   36]
 [ -39   36   65]]


[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]


In [156]:
def get_matrix_product_tran(matrix1, matrix2):
  try:
    matrix1 = np.transpose(matrix1)
    result = [[sum([matrix1[i,j]*matrix2[j,k] for j in range(matrix1.shape[1])]) for k in range(matrix2.shape[1])] for i in range(matrix1.shape[0])]
    result = np.array(result).reshape(matrix1.shape[0], matrix2.shape[1])
  except IndexError:
    print('Error: cannot calculate matrix product by the matrix combination you inputted.')
    print('matrix1: {} rows {} columns'.format(matrix1.shape[0], matrix1.shape[1]))
    print('matrix2: {} rows {} columns'.format(matrix2.shape[0], matrix2.shape[1]))
  return result

In [157]:
h = get_matrix_product_t(e_ndarray, e_ndarray)
print(h)
print('\n')
h2 = get_matrix_product_t(d_ndarray, e_ndarray)
print(h2)

[[ 117 -102  -39]
 [-102   89   36]
 [ -39   36   65]]


[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]


## いろいろな正誤判定方法

In [159]:
print(np.array_equal(g,h))

True


In [160]:
print(np.allclose(g,h))

True


In [165]:
print(np.isclose(g,h))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [167]:
print(g==h)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


[リファレンス：numpyの要素比較](https://note.nkmk.me/python-numpy-ndarray-compare/)

---

